import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import AnimatedCursor from "react-animated-cursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Edudoc - Expand Your Learning",
  description: "Generated by Aryan & Deepak",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          
          {children}
          <Analytics />
          <SpeedInsights />
          <AnimatedCursor color="193, 193, 0"
            innerScale={0.5}
            outerScale={3}
            outerSize={15}
            outerAlpha={0.4}
            
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
